// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Enitites.Models;

public partial class StockDatum
{
    public int StockId { get; set; }

    public int JobId { get; set; }

    public string StockSymbol { get; set; }

    public string DataType { get; set; }

    public TimeSpan FetchInterval { get; set; }

    public DateTime? LastFetched { get; set; }

    public virtual Job Job { get; set; }

    public virtual ICollection<UserStock> UserStocks { get; set; } = new List<UserStock>();
}